import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionContext, SessionProvider } from "next-auth/react";
import AuthSession from "./_lib/next-auth/NextAuthSession";
import { Fragment } from "react";
import Header from "./components/organism/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <AuthSession>
        <html lang="ko">
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </html>
      </AuthSession>
    </Fragment>
  );
}
